create table if not exists public.artifacts (
  id bigint generated by default as identity primary key,
  product text not null,
  version text not null,
  build_id text not null,
  build_target text not null,
  locale text,
  mar_url text not null,
  mar_size bigint not null,
  hash_function text not null,
  hash_value text not null,
  app_version text not null,
  display_version text not null,
  platform_version text not null,
  created_at timestamptz not null default now(),
  unique (product, version, build_target, locale)
);

create table if not exists public.ring_pointers (
  ring text primary key,
  target_version text not null,
  updated_at timestamptz not null,
  updated_by text not null,
  reason text not null,
  constraint ring_pointers_ring_check
    check (ring in ('oasis-canary', 'oasis-stable'))
);

create table if not exists public.ring_audit (
  id bigint generated by default as identity primary key,
  ring text not null,
  old_version text,
  new_version text not null,
  actor text not null,
  reason text not null,
  changed_at timestamptz not null,
  constraint ring_audit_ring_check
    check (ring in ('oasis-canary', 'oasis-stable'))
);

create index if not exists idx_artifacts_lookup
  on public.artifacts (product, version, build_target, locale);

create index if not exists idx_ring_audit_ring_id_desc
  on public.ring_audit (ring, id desc);

create or replace function public.set_ring_pointer(
  p_ring text,
  p_target_version text,
  p_actor text,
  p_reason text
)
returns table (
  ring text,
  old_version text,
  new_version text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_version text;
  v_now timestamptz := now();
begin
  if p_ring not in ('oasis-canary', 'oasis-stable') then
    raise exception 'ring not allowed: %', p_ring;
  end if;

  select rp.target_version
    into v_old_version
  from public.ring_pointers rp
  where rp.ring = p_ring
  for update;

  insert into public.ring_pointers (ring, target_version, updated_at, updated_by, reason)
  values (p_ring, p_target_version, v_now, p_actor, p_reason)
  on conflict (ring) do update
    set target_version = excluded.target_version,
        updated_at = excluded.updated_at,
        updated_by = excluded.updated_by,
        reason = excluded.reason;

  insert into public.ring_audit (ring, old_version, new_version, actor, reason, changed_at)
  values (p_ring, v_old_version, p_target_version, p_actor, p_reason, v_now);

  ring := p_ring;
  old_version := v_old_version;
  new_version := p_target_version;
  updated_at := v_now;
  return next;
end;
$$;

revoke all on function public.set_ring_pointer(text, text, text, text) from public;
grant execute on function public.set_ring_pointer(text, text, text, text) to service_role;
